api_active: 0
api_darksky: darksky
api_fpt: fpt
domain: https://domain.duckdns.org
google_application_credentials: botallis.json
hass_password: pass
hotword: jarvis,jarvis,subex
led_do: 15
led_xanh: 14
longlived-token: abc
model:
- jarvis.umdl
- subex.umdl
reminder: 1
sensitivity:
- 0.6
- 0.6
- 0.7
stand_alone: 0
tts: google
version_above084: right
voice: leminh
spotify: 0
spotify_username: abc@gmail.com
spotify_client_id: 
spotify_client_secret: 
