# nếu bản 0.84 trở lên thì nhập right, không thì nhập left
version_above084: right
# nhập vào đường dẫn vào hass đang hoạt động, luôn cả https,http và port nếu có
domain: https://yourdomain.duckdns.org
# nếu version trên 0.84 thì nhập long-lived token, dưới 0.84 thì nhập trong hass_password
hass_password: pass
longlived-token:abc 
# model là file training giọng nói trên snowboy
model: [jarvis.umdl,subex.umdl]
hotword: jarvis,jarvis,subex
sensitivity: [0.60,0.60,0.7]
# giọng trả lời, api của fpt, các bạn tự đăng ký lấy api để dùng cho riêng mình (để nhanh là ổn định)
# male, female
voice: leminh 
api_fpt: fpt
# api darksky để lấy thông tin thời tiết (tự đăng ký hoặc lấy bên hass đưa vào)
api_darksky: darksky
# file credential của google (tự đăng ký)
google_application_credentials: bot.json
led_do: 15
led_xanh: 14
reminder: 1
stand_alone: 0
api_active: 0
tts: google
